# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cacheable_flash"
  s.version = "0.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter H. Boling", "Brian Takita"]
  s.date = "2012-06-21"
  s.description = "Allows caching of pages with flash messages by rendering flash\nmessages from a cookie using JavaScript, instead of statically in your Rails\nview template.  Flash contents are converted to JSON and placed in\na cookie by an after_filter in a controller."
  s.email = "peter.boling@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGES",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/images/cacheable_flash/.gitkeep",
    "app/assets/javascripts/cacheable_flash/application.js",
    "app/assets/stylesheets/cacheable_flash/application.css",
    "app/controllers/cacheable-flash/application_controller.rb",
    "app/helpers/cacheable_flash/application_helper.rb",
    "app/views/layouts/cacheable-flash/application.html.erb",
    "cacheable_flash.gemspec",
    "config/routes.rb",
    "init.rb",
    "install.rb",
    "lib/cacheable_flash.rb",
    "lib/cacheable_flash/engine.rb",
    "lib/cacheable_flash/railtie.rb",
    "lib/cacheable_flash/version.rb",
    "lib/generators/cacheable_flash/install/install_generator.rb",
    "lib/tasks/cacheable-flash_tasks.rake",
    "script/rails",
    "spec/cacheable_flash/cacheable_flash_spec.rb",
    "spec/cacheable_flash/install_spec.rb",
    "spec/cacheable_flash/test_helpers_spec.rb",
    "spec/controllers/dummy_controller_spec.rb",
    "spec/dummy/README.rdoc",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/dummy_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/mailers/.gitkeep",
    "spec/dummy/app/models/.gitkeep",
    "spec/dummy/app/views/dummy/index.html.erb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/lib/assets/.gitkeep",
    "spec/dummy/log/.gitkeep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/script/rails",
    "spec/js_unit/cookie_test.html",
    "spec/js_unit/flash_test.html",
    "spec/spec_helper.rb",
    "spec/support/test_helpers.rb",
    "tasks/cacheable_flash_tasks.rake",
    "vendor/assets/javascripts/flash.js",
    "vendor/assets/javascripts/jquery.cookie.js"
  ]
  s.homepage = "http://github.com/pivotal/cacheable-flash"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Render flash messages from a cookie using JavaScript, instead of in your Rails view template"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.1.3"])
      s.add_development_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.21"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<reek>, [">= 1.2.8"])
      s.add_development_dependency(%q<roodi>, [">= 2.1.0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.1.3"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.21"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<reek>, [">= 1.2.8"])
      s.add_dependency(%q<roodi>, [">= 2.1.0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.1.3"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.21"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<reek>, [">= 1.2.8"])
    s.add_dependency(%q<roodi>, [">= 2.1.0"])
  end
end

